### PR TITLE
Switch to adafruit_bus_device dependency

### LINKED ISSUE #20: Switch to BusDevice dependency
It looks like BusDevice can now handle inverted CS pins, I took a quick look and it should be doable for this library.  The applicable comment in the library seems to be from before the PR to BusDevice that added that functionality.

### PR DESCRIPTION
**Pull request by tekktrik**
Since `adafruit_bus_device.spi_device.SPIDevice` can now handle inverted CS pins, this PR switches it over to using it!  Also should add everything needed in the infrastructure and documentation to support this change.

Resolves #20 

Still needs to be tested.

### CODE REVIEW

**Review by FoamyGuy — APPROVED** [review]
Code change makes sense and looks good to me.

I don't have the Sharp display to test it though. Will leave open for now, hopefully we can get someone with the display to try it out.

**Review by jepler — COMMENTED** [review]
Seems fine, also didn't test. Thank you!

**Comment by tekktrik** [comment]
Should I wait for a test or go ahead and merge with the approvals?

**Review by FoamyGuy — APPROVED** [review]
I merged main to resolve conflicts and tested this successfully on Feather RP2040 with https://www.adafruit.com/product/3502 using the simpletest example in this repo. Everything is working as intended as far as I can tell.

**Pull request merged**
